	std::cout << "\033[1;33mBureaucrat with 145 access\033[0m\n" << std::endl;
	Bureaucrat bcb("A", 145);
	std::cout << "\033[1;32mTrying to execute ShrubberyCreationForm\033[0m\n";
	ShrubberyCreationForm scform1("home1");
	scform1.execute(bcb);
	bcb.executeForm(scform1);
	std::cout << "\033[1;32msigning it\033[0m\n";
	bcb.signForm(scform1);
	scform1.execute(bcb);
	bcb.executeForm(scform1);
	std::cout << "\033[1;32mTrying to execute RobotomyRequestForm\033[0m\n";
	RobotomyRequestForm rrform1("home2");
	rrform1.execute(bcb);
	bcb.executeForm(rrform1);
	std::cout << "\033[1;32msigning it\033[0m\n";
	bcb.signForm(rrform1);
	rrform1.execute(bcb);
	bcb.executeForm(rrform1);
	std::cout << std::endl;
	std::cout << "\033[1;32mTrying to execute PresidentialPardonForm\033[0m\n";
	PresidentialPardonForm ppform1("home2");
	ppform1.execute(bcb);
	bcb.executeForm(ppform1);
	std::cout << "\033[1;32msigning it\033[0m\n";
	bcb.signForm(ppform1);
	ppform1.execute(bcb);
	bcb.executeForm(ppform1);
	std::cout << std::endl;